// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by SoftDreams Developer
// **************************************************************************
// ignore_for_file: constant_identifier_names

class Assets {
  const Assets._();
  static const String package = 'do_an_application';

  static const String ASSETS_FONTS_NUNITOSANS_BOLD_TTF =
      'assets/fonts/NunitoSans-Bold.ttf';

  static const String ASSETS_FONTS_NUNITOSANS_EXTRABOLD_TTF =
      'assets/fonts/NunitoSans-ExtraBold.ttf';

  static const String ASSETS_FONTS_NUNITOSANS_REGULAR_TTF =
      'assets/fonts/NunitoSans-Regular.ttf';

  static const String ASSETS_FONTS_NUNITOSANS_SEMIBOLD_TTF =
      'assets/fonts/NunitoSans-SemiBold.ttf';

  /// {@macro assets_generator.ASSETS_ICONS_ADD_CIRCLE_SVG.preview}
  static const String ASSETS_ICONS_ADD_CIRCLE_SVG =
      'assets/icons/add_circle.svg';

  /// {@macro assets_generator.ASSETS_ICONS_CHECK_BOX_SELECTED_SVG.preview}
  static const String ASSETS_ICONS_CHECK_BOX_SELECTED_SVG =
      'assets/icons/check_box_selected.svg';

  /// {@macro assets_generator.ASSETS_ICONS_CHECK_BOX_UNSELECTED_SVG.preview}
  static const String ASSETS_ICONS_CHECK_BOX_UNSELECTED_SVG =
      'assets/icons/check_box_unselected.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ENGLAND_FLAG_JPG.preview}
  static const String ASSETS_ICONS_ENGLAND_FLAG_JPG =
      'assets/icons/england_flag.jpg';

  /// {@macro assets_generator.ASSETS_ICONS_FACEBOOK_ICON_PNG.preview}
  static const String ASSETS_ICONS_FACEBOOK_ICON_PNG =
      'assets/icons/facebook_icon.png';

  /// {@macro assets_generator.ASSETS_ICONS_FILTER_SVG.preview}
  static const String ASSETS_ICONS_FILTER_SVG = 'assets/icons/filter.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ABOUT_SDS_SVG.preview}
  static const String ASSETS_ICONS_IC_ABOUT_SDS_SVG =
      'assets/icons/ic_about_sds.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ADD_SVG.preview}
  static const String ASSETS_ICONS_IC_ADD_SVG = 'assets/icons/ic_add.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_APP_SETTING_SVG.preview}
  static const String ASSETS_ICONS_IC_APP_SETTING_SVG =
      'assets/icons/ic_app_setting.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_APPROVE_INVOICE_SVG.preview}
  static const String ASSETS_ICONS_IC_APPROVE_INVOICE_SVG =
      'assets/icons/ic_approve_invoice.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ARROW_RIGHT_SVG.preview}
  static const String ASSETS_ICONS_IC_ARROW_RIGHT_SVG =
      'assets/icons/ic_arrow_right.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_BARCODE_SVG.preview}
  static const String ASSETS_ICONS_IC_BARCODE_SVG =
      'assets/icons/ic_barcode.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_BELL_CIRCLE_SVG.preview}
  static const String ASSETS_ICONS_IC_BELL_CIRCLE_SVG =
      'assets/icons/ic_bell_circle.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_BELL_CIRCLE_DARK_SVG.preview}
  static const String ASSETS_ICONS_IC_BELL_CIRCLE_DARK_SVG =
      'assets/icons/ic_bell_circle_dark.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_CANCEL_INVOICE_BIG_SVG.preview}
  static const String ASSETS_ICONS_IC_CANCEL_INVOICE_BIG_SVG =
      'assets/icons/ic_cancel_invoice_big.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_CART_SVG.preview}
  static const String ASSETS_ICONS_IC_CART_SVG = 'assets/icons/ic_cart.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_CHANGE_PASSWORD_SVG.preview}
  static const String ASSETS_ICONS_IC_CHANGE_PASSWORD_SVG =
      'assets/icons/ic_change_password.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_CLEAR_SVG.preview}
  static const String ASSETS_ICONS_IC_CLEAR_SVG = 'assets/icons/ic_clear.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_CLOSE_SNACKBAR_SVG.preview}
  static const String ASSETS_ICONS_IC_CLOSE_SNACKBAR_SVG =
      'assets/icons/ic_close_snackbar.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_COMPANY_SVG.preview}
  static const String ASSETS_ICONS_IC_COMPANY_SVG =
      'assets/icons/ic_company.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_COMPANY_LIGHT_SVG.preview}
  static const String ASSETS_ICONS_IC_COMPANY_LIGHT_SVG =
      'assets/icons/ic_company_light.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_CONFIG_INVOICE_SVG.preview}
  static const String ASSETS_ICONS_IC_CONFIG_INVOICE_SVG =
      'assets/icons/ic_config_invoice.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_CREATE_MINUS_BIG_SVG.preview}
  static const String ASSETS_ICONS_IC_CREATE_MINUS_BIG_SVG =
      'assets/icons/ic_create_minus_big.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_CUSTOMER_SVG.preview}
  static const String ASSETS_ICONS_IC_CUSTOMER_SVG =
      'assets/icons/ic_customer.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_CUSTOMER_PROFILE_SVG.preview}
  static const String ASSETS_ICONS_IC_CUSTOMER_PROFILE_SVG =
      'assets/icons/ic_customer_profile.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_DASHBOARD_SELECTED_SVG.preview}
  static const String ASSETS_ICONS_IC_DASHBOARD_SELECTED_SVG =
      'assets/icons/ic_dashboard_selected.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_DASHBOARD_UNSELECTED_SVG.preview}
  static const String ASSETS_ICONS_IC_DASHBOARD_UNSELECTED_SVG =
      'assets/icons/ic_dashboard_unselected.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_DECLARATION_CHECKBOX_SVG.preview}
  static const String ASSETS_ICONS_IC_DECLARATION_CHECKBOX_SVG =
      'assets/icons/ic_declaration_checkbox.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_DECLARATION_HISTORY_SVG.preview}
  static const String ASSETS_ICONS_IC_DECLARATION_HISTORY_SVG =
      'assets/icons/ic_declaration_history.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_DELETE_DARK_SVG.preview}
  static const String ASSETS_ICONS_IC_DELETE_DARK_SVG =
      'assets/icons/ic_delete_dark.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_DELETE_INVOICE_SVG.preview}
  static const String ASSETS_ICONS_IC_DELETE_INVOICE_SVG =
      'assets/icons/ic_delete_invoice.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_DELETE_INVOICE_BIG_SVG.preview}
  static const String ASSETS_ICONS_IC_DELETE_INVOICE_BIG_SVG =
      'assets/icons/ic_delete_invoice_big.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_DELETE_LIGHT_SVG.preview}
  static const String ASSETS_ICONS_IC_DELETE_LIGHT_SVG =
      'assets/icons/ic_delete_light.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_DUPLICATE_INVOICE_BIG_SVG.preview}
  static const String ASSETS_ICONS_IC_DUPLICATE_INVOICE_BIG_SVG =
      'assets/icons/ic_duplicate_invoice_big.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_EASY_INVOICE_LOGO_LOGIN_SVG.preview}
  static const String ASSETS_ICONS_IC_EASY_INVOICE_LOGO_LOGIN_SVG =
      'assets/icons/ic_easy_invoice_logo_login.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_EASY_INVOICE_LOGO_LOGIN_DARK_SVG.preview}
  static const String ASSETS_ICONS_IC_EASY_INVOICE_LOGO_LOGIN_DARK_SVG =
      'assets/icons/ic_easy_invoice_logo_login_dark.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_EASY_INVOICE_LOGO_SPLASH_SVG.preview}
  static const String ASSETS_ICONS_IC_EASY_INVOICE_LOGO_SPLASH_SVG =
      'assets/icons/ic_easy_invoice_logo_splash.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_EASY_INVOICE_LOGO_SPLASH_DARK_SVG.preview}
  static const String ASSETS_ICONS_IC_EASY_INVOICE_LOGO_SPLASH_DARK_SVG =
      'assets/icons/ic_easy_invoice_logo_splash_dark.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_EDIT_INVOICE_BIG_SVG.preview}
  static const String ASSETS_ICONS_IC_EDIT_INVOICE_BIG_SVG =
      'assets/icons/ic_edit_invoice_big.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_EMAIL_SVG.preview}
  static const String ASSETS_ICONS_IC_EMAIL_SVG = 'assets/icons/ic_email.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_EMAIL_HISTORY_SVG.preview}
  static const String ASSETS_ICONS_IC_EMAIL_HISTORY_SVG =
      'assets/icons/ic_email_history.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ENTERPRISE_SVG.preview}
  static const String ASSETS_ICONS_IC_ENTERPRISE_SVG =
      'assets/icons/ic_enterprise.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ERROR_NOTICE_DETAIL_DELETE_SVG.preview}
  static const String ASSETS_ICONS_IC_ERROR_NOTICE_DETAIL_DELETE_SVG =
      'assets/icons/ic_error_notice_detail_delete.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ERROR_NOTICE_DETAIL_EDIT_SVG.preview}
  static const String ASSETS_ICONS_IC_ERROR_NOTICE_DETAIL_EDIT_SVG =
      'assets/icons/ic_error_notice_detail_edit.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ERROR_NOTICE_DETAIL_SEND_SVG.preview}
  static const String ASSETS_ICONS_IC_ERROR_NOTICE_DETAIL_SEND_SVG =
      'assets/icons/ic_error_notice_detail_send.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ERROR_NOTICE_DETAIL_VIEW_SAMPLE_SVG.preview}
  static const String ASSETS_ICONS_IC_ERROR_NOTICE_DETAIL_VIEW_SAMPLE_SVG =
      'assets/icons/ic_error_notice_detail_view_sample.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_EYE_SVG.preview}
  static const String ASSETS_ICONS_IC_EYE_SVG = 'assets/icons/ic_eye.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_FACEBOOK_SVG.preview}
  static const String ASSETS_ICONS_IC_FACEBOOK_SVG =
      'assets/icons/ic_facebook.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_GUIDE_SVG.preview}
  static const String ASSETS_ICONS_IC_GUIDE_SVG = 'assets/icons/ic_guide.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_HIDE_PASSWORD_SVG.preview}
  static const String ASSETS_ICONS_IC_HIDE_PASSWORD_SVG =
      'assets/icons/ic_hide_password.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_INVOICE_ERROR_NOTICE_SVG.preview}
  static const String ASSETS_ICONS_IC_INVOICE_ERROR_NOTICE_SVG =
      'assets/icons/ic_invoice_error_notice.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_INVOICE_ERROR_NOTICE_BIG_SVG.preview}
  static const String ASSETS_ICONS_IC_INVOICE_ERROR_NOTICE_BIG_SVG =
      'assets/icons/ic_invoice_error_notice_big.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_INVOICE_SELECTED_SVG.preview}
  static const String ASSETS_ICONS_IC_INVOICE_SELECTED_SVG =
      'assets/icons/ic_invoice_selected.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_INVOICE_UNSELECTED_SVG.preview}
  static const String ASSETS_ICONS_IC_INVOICE_UNSELECTED_SVG =
      'assets/icons/ic_invoice_unselected.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_LOCATION_SVG.preview}
  static const String ASSETS_ICONS_IC_LOCATION_SVG =
      'assets/icons/ic_location.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_LOGIN_FACEBOOK_SVG.preview}
  static const String ASSETS_ICONS_IC_LOGIN_FACEBOOK_SVG =
      'assets/icons/ic_login_facebook.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_LOGIN_HELP_SVG.preview}
  static const String ASSETS_ICONS_IC_LOGIN_HELP_SVG =
      'assets/icons/ic_login_help.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_LOGIN_SEARCH_SVG.preview}
  static const String ASSETS_ICONS_IC_LOGIN_SEARCH_SVG =
      'assets/icons/ic_login_search.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_LOGOUT_SVG.preview}
  static const String ASSETS_ICONS_IC_LOGOUT_SVG = 'assets/icons/ic_logout.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_MANAGE_ERROR_NOTICE_SVG.preview}
  static const String ASSETS_ICONS_IC_MANAGE_ERROR_NOTICE_SVG =
      'assets/icons/ic_manage_error_notice.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_MST_SVG.preview}
  static const String ASSETS_ICONS_IC_MST_SVG = 'assets/icons/ic_mst.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_NEWS_SVG.preview}
  static const String ASSETS_ICONS_IC_NEWS_SVG = 'assets/icons/ic_news.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_NEXT_STEP_SVG.preview}
  static const String ASSETS_ICONS_IC_NEXT_STEP_SVG =
      'assets/icons/ic_next_step.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_NOTIFICATION_SELECTED_SVG.preview}
  static const String ASSETS_ICONS_IC_NOTIFICATION_SELECTED_SVG =
      'assets/icons/ic_notification_selected.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_NOTIFICATION_UNSELECTED_SVG.preview}
  static const String ASSETS_ICONS_IC_NOTIFICATION_UNSELECTED_SVG =
      'assets/icons/ic_notification_unselected.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_PHONE_SVG.preview}
  static const String ASSETS_ICONS_IC_PHONE_SVG = 'assets/icons/ic_phone.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_PHONE_PROFILE_SVG.preview}
  static const String ASSETS_ICONS_IC_PHONE_PROFILE_SVG =
      'assets/icons/ic_phone_profile.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_PROCESS_INVOICE_BIG_SVG.preview}
  static const String ASSETS_ICONS_IC_PROCESS_INVOICE_BIG_SVG =
      'assets/icons/ic_process_invoice_big.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_PROFILE_SVG.preview}
  static const String ASSETS_ICONS_IC_PROFILE_SVG =
      'assets/icons/ic_profile.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_PROFILE_SELECTED_SVG.preview}
  static const String ASSETS_ICONS_IC_PROFILE_SELECTED_SVG =
      'assets/icons/ic_profile_selected.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_PROFILE_UNSELECTED_SVG.preview}
  static const String ASSETS_ICONS_IC_PROFILE_UNSELECTED_SVG =
      'assets/icons/ic_profile_unselected.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_QUESTION_MARK_CIRCLE_SVG.preview}
  static const String ASSETS_ICONS_IC_QUESTION_MARK_CIRCLE_SVG =
      'assets/icons/ic_question_mark_circle.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_QUESTION_MARK_CIRCLE_DARK_SVG.preview}
  static const String ASSETS_ICONS_IC_QUESTION_MARK_CIRCLE_DARK_SVG =
      'assets/icons/ic_question_mark_circle_dark.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_RATE_APP_SVG.preview}
  static const String ASSETS_ICONS_IC_RATE_APP_SVG =
      'assets/icons/ic_rate_app.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_RECENT_EMAIL_SMALL_SVG.preview}
  static const String ASSETS_ICONS_IC_RECENT_EMAIL_SMALL_SVG =
      'assets/icons/ic_recent_email_small.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_RECENT_SEARCH_SVG.preview}
  static const String ASSETS_ICONS_IC_RECENT_SEARCH_SVG =
      'assets/icons/ic_recent_search.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_RELEASE_INVOICE_SVG.preview}
  static const String ASSETS_ICONS_IC_RELEASE_INVOICE_SVG =
      'assets/icons/ic_release_invoice.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_RELEASE_INVOICE_BIG_SVG.preview}
  static const String ASSETS_ICONS_IC_RELEASE_INVOICE_BIG_SVG =
      'assets/icons/ic_release_invoice_big.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_REPLACE_INVOICE_BIG_SVG.preview}
  static const String ASSETS_ICONS_IC_REPLACE_INVOICE_BIG_SVG =
      'assets/icons/ic_replace_invoice_big.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_RESULT_BIG_SVG.preview}
  static const String ASSETS_ICONS_IC_RESULT_BIG_SVG =
      'assets/icons/ic_result_big.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_SAVE_INVOICE_SVG.preview}
  static const String ASSETS_ICONS_IC_SAVE_INVOICE_SVG =
      'assets/icons/ic_save_invoice.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_SEARCH_BIG_SVG.preview}
  static const String ASSETS_ICONS_IC_SEARCH_BIG_SVG =
      'assets/icons/ic_search_big.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_SEARCH_HISTORY_SVG.preview}
  static const String ASSETS_ICONS_IC_SEARCH_HISTORY_SVG =
      'assets/icons/ic_search_history.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_SEARCH_INVOICE_SVG.preview}
  static const String ASSETS_ICONS_IC_SEARCH_INVOICE_SVG =
      'assets/icons/ic_search_invoice.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_SECURITY_SAFE_SVG.preview}
  static const String ASSETS_ICONS_IC_SECURITY_SAFE_SVG =
      'assets/icons/ic_security_safe.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_SEND_AND_RELEASE_INVOICE_SVG.preview}
  static const String ASSETS_ICONS_IC_SEND_AND_RELEASE_INVOICE_SVG =
      'assets/icons/ic_send_and_release_invoice.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_SEND_EMAIL_BIG_SVG.preview}
  static const String ASSETS_ICONS_IC_SEND_EMAIL_BIG_SVG =
      'assets/icons/ic_send_email_big.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_SERI_SVG.preview}
  static const String ASSETS_ICONS_IC_SERI_SVG = 'assets/icons/ic_seri.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_SETTING_SVG.preview}
  static const String ASSETS_ICONS_IC_SETTING_SVG =
      'assets/icons/ic_setting.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_SHARE_SVG.preview}
  static const String ASSETS_ICONS_IC_SHARE_SVG = 'assets/icons/ic_share.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_SHOW_PASSWORD_SVG.preview}
  static const String ASSETS_ICONS_IC_SHOW_PASSWORD_SVG =
      'assets/icons/ic_show_password.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_SPLASH_SVG.preview}
  static const String ASSETS_ICONS_IC_SPLASH_SVG = 'assets/icons/ic_splash.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_SPLASH_DARK_SVG.preview}
  static const String ASSETS_ICONS_IC_SPLASH_DARK_SVG =
      'assets/icons/ic_splash_dark.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_STAR_CIRCLE_SVG.preview}
  static const String ASSETS_ICONS_IC_STAR_CIRCLE_SVG =
      'assets/icons/ic_star_circle.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_STAR_CIRCLE_DARK_SVG.preview}
  static const String ASSETS_ICONS_IC_STAR_CIRCLE_DARK_SVG =
      'assets/icons/ic_star_circle_dark.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_UP_FILE_SVG.preview}
  static const String ASSETS_ICONS_IC_UP_FILE_SVG =
      'assets/icons/ic_up_file.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_USERNAME_SVG.preview}
  static const String ASSETS_ICONS_IC_USERNAME_SVG =
      'assets/icons/ic_username.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_VERSION_HISTORY_SVG.preview}
  static const String ASSETS_ICONS_IC_VERSION_HISTORY_SVG =
      'assets/icons/ic_version_history.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_VERSION_NUMBER_SVG.preview}
  static const String ASSETS_ICONS_IC_VERSION_NUMBER_SVG =
      'assets/icons/ic_version_number.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_VIEW_DECLARATION_SVG.preview}
  static const String ASSETS_ICONS_IC_VIEW_DECLARATION_SVG =
      'assets/icons/ic_view_declaration.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_VIEW_INVOICE_SVG.preview}
  static const String ASSETS_ICONS_IC_VIEW_INVOICE_SVG =
      'assets/icons/ic_view_invoice.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_VIEW_INVOICE_BIG_SVG.preview}
  static const String ASSETS_ICONS_IC_VIEW_INVOICE_BIG_SVG =
      'assets/icons/ic_view_invoice_big.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_YOUTUBE_SVG.preview}
  static const String ASSETS_ICONS_IC_YOUTUBE_SVG =
      'assets/icons/ic_youtube.svg';

  /// {@macro assets_generator.ASSETS_ICONS_IC_ZALO_SVG.preview}
  static const String ASSETS_ICONS_IC_ZALO_SVG = 'assets/icons/ic_zalo.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICONEI_PNG.preview}
  static const String ASSETS_ICONS_ICONEI_PNG = 'assets/icons/iconEI.png';

  /// {@macro assets_generator.ASSETS_ICONS_ICONSDS_PNG.preview}
  static const String ASSETS_ICONS_ICONSDS_PNG = 'assets/icons/iconSDS.png';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_ADD_SVG.preview}
  static const String ASSETS_ICONS_ICON_ADD_SVG = 'assets/icons/icon_add.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_ADVANCED_SVG.preview}
  static const String ASSETS_ICONS_ICON_ADVANCED_SVG =
      'assets/icons/icon_advanced.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_ADVANCED_SELECT_SVG.preview}
  static const String ASSETS_ICONS_ICON_ADVANCED_SELECT_SVG =
      'assets/icons/icon_advanced_select.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_CALENDAR_SVG.preview}
  static const String ASSETS_ICONS_ICON_CALENDAR_SVG =
      'assets/icons/icon_calendar.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_CLOCK_SVG.preview}
  static const String ASSETS_ICONS_ICON_CLOCK_SVG =
      'assets/icons/icon_clock.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_CLOCK_HISTORY_SVG.preview}
  static const String ASSETS_ICONS_ICON_CLOCK_HISTORY_SVG =
      'assets/icons/icon_clock_history.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_HOME_SVG.preview}
  static const String ASSETS_ICONS_ICON_HOME_SVG = 'assets/icons/icon_home.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_HOME_SELECT_SVG.preview}
  static const String ASSETS_ICONS_ICON_HOME_SELECT_SVG =
      'assets/icons/icon_home_select.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_NOTIFICATION_SVG.preview}
  static const String ASSETS_ICONS_ICON_NOTIFICATION_SVG =
      'assets/icons/icon_notification.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_NOTIFICATION_SELECT_SVG.preview}
  static const String ASSETS_ICONS_ICON_NOTIFICATION_SELECT_SVG =
      'assets/icons/icon_notification_select.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_PROFILE_SVG.preview}
  static const String ASSETS_ICONS_ICON_PROFILE_SVG =
      'assets/icons/icon_profile.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_PROFILE_SELECT_SVG.preview}
  static const String ASSETS_ICONS_ICON_PROFILE_SELECT_SVG =
      'assets/icons/icon_profile_select.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SEARCH_SVG.preview}
  static const String ASSETS_ICONS_ICON_SEARCH_SVG =
      'assets/icons/icon_search.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SELECT_LEFT_SVG.preview}
  static const String ASSETS_ICONS_ICON_SELECT_LEFT_SVG =
      'assets/icons/icon_select_left.svg';

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SUP_PNG.preview}
  static const String ASSETS_ICONS_ICON_SUP_PNG = 'assets/icons/icon_sup.png';

  /// {@macro assets_generator.ASSETS_ICONS_MENU_ALT_SVG.preview}
  static const String ASSETS_ICONS_MENU_ALT_SVG = 'assets/icons/menu_alt.svg';

  /// {@macro assets_generator.ASSETS_ICONS_PHONE_ICON_PNG.preview}
  static const String ASSETS_ICONS_PHONE_ICON_PNG =
      'assets/icons/phone_icon.png';

  /// {@macro assets_generator.ASSETS_ICONS_VIETNAM_FLAG_PNG.preview}
  static const String ASSETS_ICONS_VIETNAM_FLAG_PNG =
      'assets/icons/vietnam_flag.png';

  /// {@macro assets_generator.ASSETS_ICONS_YOUTUBE_ICON_PNG.preview}
  static const String ASSETS_ICONS_YOUTUBE_ICON_PNG =
      'assets/icons/youtube_icon.png';

  /// {@macro assets_generator.ASSETS_ICONS_ZALO_ICON_PNG.preview}
  static const String ASSETS_ICONS_ZALO_ICON_PNG = 'assets/icons/zalo_icon.png';

  /// {@macro assets_generator.ASSETS_IMAGES_EMPTY_FOLDER_PNG.preview}
  static const String ASSETS_IMAGES_EMPTY_FOLDER_PNG =
      'assets/images/empty-folder.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ERROR_JPG.preview}
  static const String ASSETS_IMAGES_ERROR_JPG = 'assets/images/error.jpg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_HRM_PNG.preview}
  static const String ASSETS_IMAGES_ICON_HRM_PNG = 'assets/images/icon_hrm.png';

  /// {@macro assets_generator.ASSETS_IMAGES_IMAGE_PNG.preview}
  static const String ASSETS_IMAGES_IMAGE_PNG = 'assets/images/image.png';

  /// {@macro assets_generator.ASSETS_IMAGES_IMAGE_DEFAULT_JPG.preview}
  static const String ASSETS_IMAGES_IMAGE_DEFAULT_JPG =
      'assets/images/image_default.jpg';

  /// {@macro assets_generator.ASSETS_IMAGES_LOGIN_FORM_BG_JPG.preview}
  static const String ASSETS_IMAGES_LOGIN_FORM_BG_JPG =
      'assets/images/login_form_bg.jpg';

  /// {@macro assets_generator.ASSETS_IMAGES_NEW_VERSION_PNG.preview}
  static const String ASSETS_IMAGES_NEW_VERSION_PNG =
      'assets/images/new_version.png';
}

final List<String> assetsArray = <String>[
  Assets.ASSETS_FONTS_NUNITOSANS_BOLD_TTF,
  Assets.ASSETS_FONTS_NUNITOSANS_EXTRABOLD_TTF,
  Assets.ASSETS_FONTS_NUNITOSANS_REGULAR_TTF,
  Assets.ASSETS_FONTS_NUNITOSANS_SEMIBOLD_TTF,

  /// {@macro assets_generator.ASSETS_ICONS_ADD_CIRCLE_SVG.preview}
  Assets.ASSETS_ICONS_ADD_CIRCLE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_CHECK_BOX_SELECTED_SVG.preview}
  Assets.ASSETS_ICONS_CHECK_BOX_SELECTED_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_CHECK_BOX_UNSELECTED_SVG.preview}
  Assets.ASSETS_ICONS_CHECK_BOX_UNSELECTED_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ENGLAND_FLAG_JPG.preview}
  Assets.ASSETS_ICONS_ENGLAND_FLAG_JPG,

  /// {@macro assets_generator.ASSETS_ICONS_FACEBOOK_ICON_PNG.preview}
  Assets.ASSETS_ICONS_FACEBOOK_ICON_PNG,

  /// {@macro assets_generator.ASSETS_ICONS_FILTER_SVG.preview}
  Assets.ASSETS_ICONS_FILTER_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_ABOUT_SDS_SVG.preview}
  Assets.ASSETS_ICONS_IC_ABOUT_SDS_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_ADD_SVG.preview}
  Assets.ASSETS_ICONS_IC_ADD_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_APP_SETTING_SVG.preview}
  Assets.ASSETS_ICONS_IC_APP_SETTING_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_APPROVE_INVOICE_SVG.preview}
  Assets.ASSETS_ICONS_IC_APPROVE_INVOICE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_ARROW_RIGHT_SVG.preview}
  Assets.ASSETS_ICONS_IC_ARROW_RIGHT_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_BARCODE_SVG.preview}
  Assets.ASSETS_ICONS_IC_BARCODE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_BELL_CIRCLE_SVG.preview}
  Assets.ASSETS_ICONS_IC_BELL_CIRCLE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_BELL_CIRCLE_DARK_SVG.preview}
  Assets.ASSETS_ICONS_IC_BELL_CIRCLE_DARK_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_CANCEL_INVOICE_BIG_SVG.preview}
  Assets.ASSETS_ICONS_IC_CANCEL_INVOICE_BIG_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_CART_SVG.preview}
  Assets.ASSETS_ICONS_IC_CART_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_CHANGE_PASSWORD_SVG.preview}
  Assets.ASSETS_ICONS_IC_CHANGE_PASSWORD_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_CLEAR_SVG.preview}
  Assets.ASSETS_ICONS_IC_CLEAR_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_CLOSE_SNACKBAR_SVG.preview}
  Assets.ASSETS_ICONS_IC_CLOSE_SNACKBAR_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_COMPANY_SVG.preview}
  Assets.ASSETS_ICONS_IC_COMPANY_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_COMPANY_LIGHT_SVG.preview}
  Assets.ASSETS_ICONS_IC_COMPANY_LIGHT_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_CONFIG_INVOICE_SVG.preview}
  Assets.ASSETS_ICONS_IC_CONFIG_INVOICE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_CREATE_MINUS_BIG_SVG.preview}
  Assets.ASSETS_ICONS_IC_CREATE_MINUS_BIG_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_CUSTOMER_SVG.preview}
  Assets.ASSETS_ICONS_IC_CUSTOMER_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_CUSTOMER_PROFILE_SVG.preview}
  Assets.ASSETS_ICONS_IC_CUSTOMER_PROFILE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_DASHBOARD_SELECTED_SVG.preview}
  Assets.ASSETS_ICONS_IC_DASHBOARD_SELECTED_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_DASHBOARD_UNSELECTED_SVG.preview}
  Assets.ASSETS_ICONS_IC_DASHBOARD_UNSELECTED_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_DECLARATION_CHECKBOX_SVG.preview}
  Assets.ASSETS_ICONS_IC_DECLARATION_CHECKBOX_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_DECLARATION_HISTORY_SVG.preview}
  Assets.ASSETS_ICONS_IC_DECLARATION_HISTORY_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_DELETE_DARK_SVG.preview}
  Assets.ASSETS_ICONS_IC_DELETE_DARK_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_DELETE_INVOICE_SVG.preview}
  Assets.ASSETS_ICONS_IC_DELETE_INVOICE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_DELETE_INVOICE_BIG_SVG.preview}
  Assets.ASSETS_ICONS_IC_DELETE_INVOICE_BIG_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_DELETE_LIGHT_SVG.preview}
  Assets.ASSETS_ICONS_IC_DELETE_LIGHT_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_DUPLICATE_INVOICE_BIG_SVG.preview}
  Assets.ASSETS_ICONS_IC_DUPLICATE_INVOICE_BIG_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_EASY_INVOICE_LOGO_LOGIN_SVG.preview}
  Assets.ASSETS_ICONS_IC_EASY_INVOICE_LOGO_LOGIN_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_EASY_INVOICE_LOGO_LOGIN_DARK_SVG.preview}
  Assets.ASSETS_ICONS_IC_EASY_INVOICE_LOGO_LOGIN_DARK_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_EASY_INVOICE_LOGO_SPLASH_SVG.preview}
  Assets.ASSETS_ICONS_IC_EASY_INVOICE_LOGO_SPLASH_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_EASY_INVOICE_LOGO_SPLASH_DARK_SVG.preview}
  Assets.ASSETS_ICONS_IC_EASY_INVOICE_LOGO_SPLASH_DARK_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_EDIT_INVOICE_BIG_SVG.preview}
  Assets.ASSETS_ICONS_IC_EDIT_INVOICE_BIG_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_EMAIL_SVG.preview}
  Assets.ASSETS_ICONS_IC_EMAIL_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_EMAIL_HISTORY_SVG.preview}
  Assets.ASSETS_ICONS_IC_EMAIL_HISTORY_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_ENTERPRISE_SVG.preview}
  Assets.ASSETS_ICONS_IC_ENTERPRISE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_ERROR_NOTICE_DETAIL_DELETE_SVG.preview}
  Assets.ASSETS_ICONS_IC_ERROR_NOTICE_DETAIL_DELETE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_ERROR_NOTICE_DETAIL_EDIT_SVG.preview}
  Assets.ASSETS_ICONS_IC_ERROR_NOTICE_DETAIL_EDIT_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_ERROR_NOTICE_DETAIL_SEND_SVG.preview}
  Assets.ASSETS_ICONS_IC_ERROR_NOTICE_DETAIL_SEND_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_ERROR_NOTICE_DETAIL_VIEW_SAMPLE_SVG.preview}
  Assets.ASSETS_ICONS_IC_ERROR_NOTICE_DETAIL_VIEW_SAMPLE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_EYE_SVG.preview}
  Assets.ASSETS_ICONS_IC_EYE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_FACEBOOK_SVG.preview}
  Assets.ASSETS_ICONS_IC_FACEBOOK_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_GUIDE_SVG.preview}
  Assets.ASSETS_ICONS_IC_GUIDE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_HIDE_PASSWORD_SVG.preview}
  Assets.ASSETS_ICONS_IC_HIDE_PASSWORD_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_INVOICE_ERROR_NOTICE_SVG.preview}
  Assets.ASSETS_ICONS_IC_INVOICE_ERROR_NOTICE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_INVOICE_ERROR_NOTICE_BIG_SVG.preview}
  Assets.ASSETS_ICONS_IC_INVOICE_ERROR_NOTICE_BIG_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_INVOICE_SELECTED_SVG.preview}
  Assets.ASSETS_ICONS_IC_INVOICE_SELECTED_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_INVOICE_UNSELECTED_SVG.preview}
  Assets.ASSETS_ICONS_IC_INVOICE_UNSELECTED_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_LOCATION_SVG.preview}
  Assets.ASSETS_ICONS_IC_LOCATION_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_LOGIN_FACEBOOK_SVG.preview}
  Assets.ASSETS_ICONS_IC_LOGIN_FACEBOOK_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_LOGIN_HELP_SVG.preview}
  Assets.ASSETS_ICONS_IC_LOGIN_HELP_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_LOGIN_SEARCH_SVG.preview}
  Assets.ASSETS_ICONS_IC_LOGIN_SEARCH_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_LOGOUT_SVG.preview}
  Assets.ASSETS_ICONS_IC_LOGOUT_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_MANAGE_ERROR_NOTICE_SVG.preview}
  Assets.ASSETS_ICONS_IC_MANAGE_ERROR_NOTICE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_MST_SVG.preview}
  Assets.ASSETS_ICONS_IC_MST_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_NEWS_SVG.preview}
  Assets.ASSETS_ICONS_IC_NEWS_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_NEXT_STEP_SVG.preview}
  Assets.ASSETS_ICONS_IC_NEXT_STEP_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_NOTIFICATION_SELECTED_SVG.preview}
  Assets.ASSETS_ICONS_IC_NOTIFICATION_SELECTED_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_NOTIFICATION_UNSELECTED_SVG.preview}
  Assets.ASSETS_ICONS_IC_NOTIFICATION_UNSELECTED_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_PHONE_SVG.preview}
  Assets.ASSETS_ICONS_IC_PHONE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_PHONE_PROFILE_SVG.preview}
  Assets.ASSETS_ICONS_IC_PHONE_PROFILE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_PROCESS_INVOICE_BIG_SVG.preview}
  Assets.ASSETS_ICONS_IC_PROCESS_INVOICE_BIG_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_PROFILE_SVG.preview}
  Assets.ASSETS_ICONS_IC_PROFILE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_PROFILE_SELECTED_SVG.preview}
  Assets.ASSETS_ICONS_IC_PROFILE_SELECTED_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_PROFILE_UNSELECTED_SVG.preview}
  Assets.ASSETS_ICONS_IC_PROFILE_UNSELECTED_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_QUESTION_MARK_CIRCLE_SVG.preview}
  Assets.ASSETS_ICONS_IC_QUESTION_MARK_CIRCLE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_QUESTION_MARK_CIRCLE_DARK_SVG.preview}
  Assets.ASSETS_ICONS_IC_QUESTION_MARK_CIRCLE_DARK_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_RATE_APP_SVG.preview}
  Assets.ASSETS_ICONS_IC_RATE_APP_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_RECENT_EMAIL_SMALL_SVG.preview}
  Assets.ASSETS_ICONS_IC_RECENT_EMAIL_SMALL_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_RECENT_SEARCH_SVG.preview}
  Assets.ASSETS_ICONS_IC_RECENT_SEARCH_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_RELEASE_INVOICE_SVG.preview}
  Assets.ASSETS_ICONS_IC_RELEASE_INVOICE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_RELEASE_INVOICE_BIG_SVG.preview}
  Assets.ASSETS_ICONS_IC_RELEASE_INVOICE_BIG_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_REPLACE_INVOICE_BIG_SVG.preview}
  Assets.ASSETS_ICONS_IC_REPLACE_INVOICE_BIG_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_RESULT_BIG_SVG.preview}
  Assets.ASSETS_ICONS_IC_RESULT_BIG_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_SAVE_INVOICE_SVG.preview}
  Assets.ASSETS_ICONS_IC_SAVE_INVOICE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_SEARCH_BIG_SVG.preview}
  Assets.ASSETS_ICONS_IC_SEARCH_BIG_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_SEARCH_HISTORY_SVG.preview}
  Assets.ASSETS_ICONS_IC_SEARCH_HISTORY_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_SEARCH_INVOICE_SVG.preview}
  Assets.ASSETS_ICONS_IC_SEARCH_INVOICE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_SECURITY_SAFE_SVG.preview}
  Assets.ASSETS_ICONS_IC_SECURITY_SAFE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_SEND_AND_RELEASE_INVOICE_SVG.preview}
  Assets.ASSETS_ICONS_IC_SEND_AND_RELEASE_INVOICE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_SEND_EMAIL_BIG_SVG.preview}
  Assets.ASSETS_ICONS_IC_SEND_EMAIL_BIG_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_SERI_SVG.preview}
  Assets.ASSETS_ICONS_IC_SERI_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_SETTING_SVG.preview}
  Assets.ASSETS_ICONS_IC_SETTING_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_SHARE_SVG.preview}
  Assets.ASSETS_ICONS_IC_SHARE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_SHOW_PASSWORD_SVG.preview}
  Assets.ASSETS_ICONS_IC_SHOW_PASSWORD_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_SPLASH_SVG.preview}
  Assets.ASSETS_ICONS_IC_SPLASH_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_SPLASH_DARK_SVG.preview}
  Assets.ASSETS_ICONS_IC_SPLASH_DARK_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_STAR_CIRCLE_SVG.preview}
  Assets.ASSETS_ICONS_IC_STAR_CIRCLE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_STAR_CIRCLE_DARK_SVG.preview}
  Assets.ASSETS_ICONS_IC_STAR_CIRCLE_DARK_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_UP_FILE_SVG.preview}
  Assets.ASSETS_ICONS_IC_UP_FILE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_USERNAME_SVG.preview}
  Assets.ASSETS_ICONS_IC_USERNAME_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_VERSION_HISTORY_SVG.preview}
  Assets.ASSETS_ICONS_IC_VERSION_HISTORY_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_VERSION_NUMBER_SVG.preview}
  Assets.ASSETS_ICONS_IC_VERSION_NUMBER_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_VIEW_DECLARATION_SVG.preview}
  Assets.ASSETS_ICONS_IC_VIEW_DECLARATION_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_VIEW_INVOICE_SVG.preview}
  Assets.ASSETS_ICONS_IC_VIEW_INVOICE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_VIEW_INVOICE_BIG_SVG.preview}
  Assets.ASSETS_ICONS_IC_VIEW_INVOICE_BIG_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_YOUTUBE_SVG.preview}
  Assets.ASSETS_ICONS_IC_YOUTUBE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_IC_ZALO_SVG.preview}
  Assets.ASSETS_ICONS_IC_ZALO_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICONEI_PNG.preview}
  Assets.ASSETS_ICONS_ICONEI_PNG,

  /// {@macro assets_generator.ASSETS_ICONS_ICONSDS_PNG.preview}
  Assets.ASSETS_ICONS_ICONSDS_PNG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_ADD_SVG.preview}
  Assets.ASSETS_ICONS_ICON_ADD_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_ADVANCED_SVG.preview}
  Assets.ASSETS_ICONS_ICON_ADVANCED_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_ADVANCED_SELECT_SVG.preview}
  Assets.ASSETS_ICONS_ICON_ADVANCED_SELECT_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_CALENDAR_SVG.preview}
  Assets.ASSETS_ICONS_ICON_CALENDAR_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_CLOCK_SVG.preview}
  Assets.ASSETS_ICONS_ICON_CLOCK_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_CLOCK_HISTORY_SVG.preview}
  Assets.ASSETS_ICONS_ICON_CLOCK_HISTORY_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_HOME_SVG.preview}
  Assets.ASSETS_ICONS_ICON_HOME_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_HOME_SELECT_SVG.preview}
  Assets.ASSETS_ICONS_ICON_HOME_SELECT_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_NOTIFICATION_SVG.preview}
  Assets.ASSETS_ICONS_ICON_NOTIFICATION_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_NOTIFICATION_SELECT_SVG.preview}
  Assets.ASSETS_ICONS_ICON_NOTIFICATION_SELECT_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_PROFILE_SVG.preview}
  Assets.ASSETS_ICONS_ICON_PROFILE_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_PROFILE_SELECT_SVG.preview}
  Assets.ASSETS_ICONS_ICON_PROFILE_SELECT_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SEARCH_SVG.preview}
  Assets.ASSETS_ICONS_ICON_SEARCH_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SELECT_LEFT_SVG.preview}
  Assets.ASSETS_ICONS_ICON_SELECT_LEFT_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_ICON_SUP_PNG.preview}
  Assets.ASSETS_ICONS_ICON_SUP_PNG,

  /// {@macro assets_generator.ASSETS_ICONS_MENU_ALT_SVG.preview}
  Assets.ASSETS_ICONS_MENU_ALT_SVG,

  /// {@macro assets_generator.ASSETS_ICONS_PHONE_ICON_PNG.preview}
  Assets.ASSETS_ICONS_PHONE_ICON_PNG,

  /// {@macro assets_generator.ASSETS_ICONS_VIETNAM_FLAG_PNG.preview}
  Assets.ASSETS_ICONS_VIETNAM_FLAG_PNG,

  /// {@macro assets_generator.ASSETS_ICONS_YOUTUBE_ICON_PNG.preview}
  Assets.ASSETS_ICONS_YOUTUBE_ICON_PNG,

  /// {@macro assets_generator.ASSETS_ICONS_ZALO_ICON_PNG.preview}
  Assets.ASSETS_ICONS_ZALO_ICON_PNG,

  /// {@macro assets_generator.ASSETS_IMAGES_EMPTY_FOLDER_PNG.preview}
  Assets.ASSETS_IMAGES_EMPTY_FOLDER_PNG,

  /// {@macro assets_generator.ASSETS_IMAGES_ERROR_JPG.preview}
  Assets.ASSETS_IMAGES_ERROR_JPG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_HRM_PNG.preview}
  Assets.ASSETS_IMAGES_ICON_HRM_PNG,

  /// {@macro assets_generator.ASSETS_IMAGES_IMAGE_PNG.preview}
  Assets.ASSETS_IMAGES_IMAGE_PNG,

  /// {@macro assets_generator.ASSETS_IMAGES_IMAGE_DEFAULT_JPG.preview}
  Assets.ASSETS_IMAGES_IMAGE_DEFAULT_JPG,

  /// {@macro assets_generator.ASSETS_IMAGES_LOGIN_FORM_BG_JPG.preview}
  Assets.ASSETS_IMAGES_LOGIN_FORM_BG_JPG,

  /// {@macro assets_generator.ASSETS_IMAGES_NEW_VERSION_PNG.preview}
  Assets.ASSETS_IMAGES_NEW_VERSION_PNG,
];
